= Spring Batch 4.x Task 2.x Boot 2.7.x Test Data generator

The tests create the DB load files for Spring Batch 4.x and Spring Cloud Task 2.x tables for a set of scenarios.

== Requirements:

* Java 8 or Above

== Create load files:

[source,shell]
----
mvn clean package
----

== Configuration
There is a CSV configuration file located at `src/test/resources/batchexportconfig.csv` with each column representing a setting that you can configure.
Thee 3 settings that allow you to change the behavior of what is produced for the load file for each test are as follows

1. Column 1 - *prefix:* Allows you to set the prefix for the task and batch tables.   Its default is `default` which means that the load scripts will use batch and task's default prefixes.
2. Column 2 - *database type:* Allows you to specify the type of database for which the load data will be created. It defaults to MARIADB, but POSTGRES is also supported.
3. Column 3 - *sequence start:* The number for which the sequences will be defaulted as their start value.  Defaults to 9000.

If you want to change the prefix for the tables open the `src/test/resources/batchexportconfig.csv` file ane replace the word `default` with your prefix.
THis will change all the prefixes for the Task and Batch tables to the specified value.  For example if you set the value in `batchexportconfig.csv` to `V3` then `TASK_EXECUTION`  would become `V3_EXECUTION`.

